version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: nectia_db
    restart: unless-stopped
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  app:
    build: .
    volumes:
      - .:/app
    container_name: nectia_app
    restart: unless-stopped
    env_file: .env
    ports:
      - $APP_PORT:$APP_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - MONGO_URL=mongodb://mongodb/$MONGODB_DATABASE
    command:  npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - mongodb

volumes:
  db: